# Generated by Django 4.0.6 on 2023-03-09 02:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CarritoCompras',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('total_carrito', models.DecimalField(decimal_places=2, max_digits=6, null=True)),
                ('idUsuario', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombres', models.CharField(max_length=20, null=True)),
                ('direccion', models.CharField(max_length=30, null=True)),
                ('pais', models.CharField(max_length=15, null=True)),
                ('cuidad', models.CharField(max_length=15, null=True)),
                ('ruc', models.DecimalField(decimal_places=0, max_digits=13, null=True)),
                ('email', models.CharField(max_length=20, null=True)),
                ('telefono', models.DecimalField(decimal_places=0, max_digits=13, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=15, null=True)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=6, null=True)),
                ('marca', models.CharField(max_length=20, null=True)),
                ('cantidad', models.IntegerField(null=True)),
                ('imagenProducto', models.ImageField(null=True, upload_to='imagenes/')),
                ('informacion', models.CharField(max_length=200, null=True)),
                ('idProveedor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Aplicacion.proveedor')),
            ],
        ),
        migrations.CreateModel(
            name='OrdenItem',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField(default=1, null=True)),
                ('total_item', models.DecimalField(decimal_places=2, default=0, max_digits=6, null=True)),
                ('idCarritoCompra', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Aplicacion.carritocompras')),
                ('idProducto', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Aplicacion.producto')),
            ],
        ),
        migrations.CreateModel(
            name='OrdenCompra',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('idCarritoCompras', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Aplicacion.carritocompras')),
                ('idUsuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('numeroFactura', models.CharField(max_length=10, null=True)),
                ('fechaFactura', models.DateField(null=True)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=6, null=True)),
                ('totalPagar', models.DecimalField(decimal_places=2, max_digits=6, null=True)),
                ('idOrdenCompra', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='Aplicacion.ordencompra')),
            ],
        ),
    ]
