# Generated by Django 4.0.6 on 2022-07-09 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Aplicacion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Administrador',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=15, null=True)),
                ('apellidos', models.CharField(max_length=15, null=True)),
                ('contacto', models.CharField(max_length=15, null=True)),
                ('email', models.EmailField(max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CarritoCompras',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('prueba', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombres', models.CharField(max_length=25, null=True)),
                ('apellidos', models.CharField(max_length=25, null=True)),
                ('nombreUsuario', models.CharField(max_length=20, null=True)),
                ('email', models.EmailField(max_length=20, null=True)),
                ('domicilio', models.CharField(max_length=15, null=True)),
                ('telefono', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('numeroFactura', models.CharField(max_length=10, null=True)),
                ('fechaFactura', models.DateField(null=True)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=6, null=True)),
                ('totalPagar', models.DecimalField(decimal_places=2, max_digits=6, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='OrdenCompra',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('prueba', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=15, null=True)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=6, null=True)),
                ('marca', models.CharField(max_length=20, null=True)),
                ('cantidad', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombres', models.CharField(max_length=20, null=True)),
                ('direccion', models.CharField(max_length=30, null=True)),
                ('pais', models.CharField(max_length=15, null=True)),
                ('cuidad', models.CharField(max_length=15, null=True)),
                ('ruc', models.DecimalField(decimal_places=0, max_digits=13, null=True)),
                ('email', models.CharField(max_length=20, null=True)),
                ('telefono', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TarjetaCredito',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('numeroTarjeta', models.CharField(max_length=10, null=True)),
                ('fechaCreacion', models.DateField(null=True)),
                ('fechaExpiracion', models.DateField(null=True)),
            ],
        ),
        migrations.RenameModel(
            old_name='Fabrica',
            new_name='Cuenta',
        ),
        migrations.RenameField(
            model_name='cuenta',
            old_name='nuc_numero',
            new_name='password',
        ),
        migrations.RenameField(
            model_name='cuenta',
            old_name='ubicacion',
            new_name='usuario',
        ),
    ]
