# Generated by Django 4.0.6 on 2023-03-09 03:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Aplicacion', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordenitem',
            name='idCarritoCompra',
        ),
    ]
