# Generated by Django 4.0.6 on 2022-07-10 01:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Aplicacion', '0003_alter_carritocompras_prueba_alter_ordencompra_prueba'),
    ]

    operations = [
        migrations.CreateModel(
            name='Suministrar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AddField(
            model_name='administrador',
            name='idCuenta',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='Aplicacion.cuenta'),
        ),
        migrations.AddField(
            model_name='carritocompras',
            name='idCliente',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='Aplicacion.cliente'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='idCuenta',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='Aplicacion.cuenta'),
        ),
        migrations.AddField(
            model_name='factura',
            name='idOrdenCompra',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='Aplicacion.ordencompra'),
        ),
        migrations.AddField(
            model_name='producto',
            name='idAdministrador',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Aplicacion.administrador'),
        ),
        migrations.AddField(
            model_name='producto',
            name='idCarritoCompras',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Aplicacion.carritocompras'),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='idAdministrador',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Aplicacion.administrador'),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='idSuministrar',
            field=models.ManyToManyField(through='Aplicacion.Suministrar', to='Aplicacion.producto'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='telefono',
            field=models.DecimalField(decimal_places=0, max_digits=13, null=True),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='telefono',
            field=models.DecimalField(decimal_places=0, max_digits=13, null=True),
        ),
        migrations.AddField(
            model_name='suministrar',
            name='idProducto',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Aplicacion.proveedor'),
        ),
        migrations.AddField(
            model_name='suministrar',
            name='idProveedor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Aplicacion.producto'),
        ),
    ]
