# Generated by Django 4.0.6 on 2022-07-10 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Aplicacion', '0004_suministrar_administrador_idcuenta_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='suministrar',
            name='suministrar',
            field=models.BooleanField(default=False),
        ),
    ]
