# Generated by Django 4.0.6 on 2022-07-10 02:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Aplicacion', '0005_suministrar_suministrar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='suministrar',
            name='suministrar',
        ),
    ]
