# Generated by Django 4.0.6 on 2022-08-03 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Aplicacion', '0008_alter_producto_imagenproducto'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='informacion',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
