# Generated by Django 4.0.6 on 2022-08-09 17:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Aplicacion', '0009_producto_informacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordencompra',
            name='idCliente',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Aplicacion.cliente'),
        ),
    ]
