# Generated by Django 4.0.6 on 2022-08-10 04:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Aplicacion', '0010_ordencompra_idcliente'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='idCuenta',
        ),
    ]
