# Generated by Django 4.0.6 on 2022-08-10 04:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Aplicacion', '0011_remove_cliente_idcuenta'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='idCarritoCompras',
        ),
    ]
