# Generated by Django 4.0.6 on 2022-08-10 05:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Aplicacion', '0012_remove_producto_idcarritocompras'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='idAdministrador',
        ),
        migrations.RemoveField(
            model_name='proveedor',
            name='idSuministrar',
        ),
        migrations.AddField(
            model_name='producto',
            name='idProveedor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Aplicacion.proveedor'),
        ),
        migrations.DeleteModel(
            name='Suministrar',
        ),
    ]
