# Generated by Django 4.0.6 on 2022-08-10 05:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Aplicacion', '0013_remove_producto_idadministrador_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proveedor',
            name='idAdministrador',
        ),
    ]
