# Generated by Django 4.0.6 on 2022-08-10 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Aplicacion', '0014_remove_proveedor_idadministrador'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='password',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
