# Generated by Django 4.0.6 on 2022-12-10 07:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Aplicacion', '0015_cliente_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carritocompras',
            name='prueba',
        ),
        migrations.AddField(
            model_name='carritocompras',
            name='idProducto',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Aplicacion.producto'),
        ),
    ]
