# Generated by Django 4.0.6 on 2022-12-11 05:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Aplicacion', '0016_remove_carritocompras_prueba_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carritocompras',
            name='idCliente',
        ),
        migrations.AddField(
            model_name='carritocompras',
            name='idUsuario',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='ordencompra',
            name='idCliente',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Cliente',
        ),
    ]
