# Generated by Django 4.0.6 on 2022-12-11 06:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Aplicacion', '0017_remove_carritocompras_idcliente_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='administrador',
            name='idCuenta',
        ),
        migrations.DeleteModel(
            name='Cuenta',
        ),
    ]
