# Generated by Django 4.0.6 on 2022-12-11 06:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Aplicacion', '0018_remove_administrador_idcuenta_delete_cuenta'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Administrador',
        ),
    ]
