# Generated by Django 4.0.6 on 2022-12-11 06:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Aplicacion', '0019_delete_administrador'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TarjetaCredito',
        ),
    ]
