# Generated by Django 4.0.6 on 2022-12-11 16:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Aplicacion', '0020_delete_tarjetacredito'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarritoProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RenameField(
            model_name='ordencompra',
            old_name='idCliente',
            new_name='idUsuario',
        ),
        migrations.RemoveField(
            model_name='carritocompras',
            name='idProducto',
        ),
        migrations.RemoveField(
            model_name='ordencompra',
            name='prueba',
        ),
        migrations.AddField(
            model_name='carritocompras',
            name='idCarritoProducto',
            field=models.ManyToManyField(through='Aplicacion.CarritoProducto', to='Aplicacion.producto'),
        ),
        migrations.AddField(
            model_name='ordencompra',
            name='idCarritoCompras',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Aplicacion.carritocompras'),
        ),
        migrations.AddField(
            model_name='carritoproducto',
            name='idCarrito',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Aplicacion.carritocompras'),
        ),
        migrations.AddField(
            model_name='carritoproducto',
            name='idProducto',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Aplicacion.producto'),
        ),
    ]
