# Generated by Django 4.0.6 on 2023-01-01 01:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Aplicacion', '0021_carritoproducto_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carritocompras',
            name='idCarritoProducto',
        ),
        migrations.AddField(
            model_name='carritocompras',
            name='idProducto',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Aplicacion.producto'),
        ),
    ]
