# Generated by Django 4.0.6 on 2023-03-07 02:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Aplicacion', '0023_remove_carritocompras_idproducto_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrdenItem',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField(null=True)),
                ('producto', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Aplicacion.producto')),
            ],
        ),
        migrations.AddField(
            model_name='carritocompras',
            name='total_pagar',
            field=models.DecimalField(decimal_places=2, max_digits=6, null=True),
        ),
        migrations.DeleteModel(
            name='CarritoProducto',
        ),
    ]
